#!/bin/bash

set -o allexport
source .env
set +o allexport

NETWORK="wordpress_internal"

docker run  --rm \
            --init \
            --volumes-from wordpress-backup-1 \
            --network $NETWORK \
            -e MARIADB_DB="${WORDPRESS_DB_NAME}" \
            -e MARIADB_HOST="${WORDPRESS_DB_HOST}" \
            -e MARIADB_USER=${WORDPRESS_DB_USER} \
            -e MARIADB_PASSWORD=${WORDPRESS_DB_PASSWORD} \
            -e BACKUP_KEEP_MINS=${BACKUP_KEEP_MINS} \
            -e BACKUP_KEEP_DAYS=${BACKUP_KEEP_DAYS} \
            -e BACKUP_KEEP_WEEKS=${BACKUP_KEEP_WEEKS} \
            -e BACKUP_KEEP_MONTHS=${BACKUP_KEEP_MONTHS} \
            atareao/mariadb-backup /backup.sh
