#!/bin/sh

set -e

function send_message(){
    MESSAGE="$@"
    TS=$(date +%s%3N)
    ENDPOINT="https://${MATRIX_HOST}/_matrix/client/v3/rooms/${MATRIX_ROOM}:${MATRIX_HOST}/send/m.room.message/${TS}"
    curl --request POST \
         --url "${WEBHOOK_URL}" \
         --header "Authorization: Bearer ${MATRIX_TOKEN}" \
         --data "{\"msgtype\": \"m.text\", \"body\": \"${MESSAGE}\"}" \
         --max-time 10 \
         --retry 5

}

# Possible actions: error, pre-backup, post-backup
ACTION="${1}"

if [ "${WEBHOOK_URL}" != "**None**" ]; then
    case "${ACTION}" in
        "error")
            echo "Execute error webhook call to ${WEBHOOK_URL}"
            send_message "Can NOT make backup from ${HOST}"
            ;;
        "pre-backup")
            echo "Going to make backup"
            ;;
        "post-backup")
            echo "Execute post-backup webhook call to ${WEBHOOK_URL}"
            send_message "Backup done from ${HOST}"
            ;;
    esac
fi
